import type { Metadata } from "next";
import { Caveat_Brush, Geist, Geist_Mono, Kablammo } from "next/font/google";
import "./globals.css";

const kablammo = Kablammo({
  variable: "--font-kablammo",
  subsets: ["latin"],
});

const caveatBrush = Caveat_Brush({
  weight: ["400"],
  variable: "--font-caveat-brush",
  subsets: ["latin"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`dark ${geistSans.variable} ${geistMono.variable} ${kablammo.variable} ${caveatBrush.variable} antialiased font-sans`}
      >
        {children}
      </body>
    </html>
  );
}
